/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    subscribers: Subscriber;
    organisations: Organisation;
    contacts: Contact;
    deals: Deal;
    'deal-stages': DealStage;
    projects: Project;
    tasks: Task;
    'task-statuses': TaskStatus;
    'content-items': ContentItem;
    'content-channels': ContentChannel;
    'knowledge-docs': KnowledgeDoc;
    activities: Activity;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    organisations: {
      contacten: 'contacts';
      deals: 'deals';
      projecten: 'projects';
    };
    contacts: {
      deals: 'deals';
    };
    projects: {
      taken: 'tasks';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    organisations: OrganisationsSelect<false> | OrganisationsSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    deals: DealsSelect<false> | DealsSelect<true>;
    'deal-stages': DealStagesSelect<false> | DealStagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    tasks: TasksSelect<false> | TasksSelect<true>;
    'task-statuses': TaskStatusesSelect<false> | TaskStatusesSelect<true>;
    'content-items': ContentItemsSelect<false> | ContentItemsSelect<true>;
    'content-channels': ContentChannelsSelect<false> | ContentChannelsSelect<true>;
    'knowledge-docs': KnowledgeDocsSelect<false> | KnowledgeDocsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-pad van de pagina. Gebruik "home" voor de homepage.
   */
  slug: string;
  layout?:
    | (
        | CalendlyEmbedBlock
        | BrushNoteBlock
        | CardColumnsBlock
        | ContentBlock
        | EbookOptinBlock
        | FaqBlock
        | HeroPhotoBlock
        | IframeEmbedBlock
        | LinkButtonsBlock
        | IconListBlock
        | StatementBlock
        | SplitPhotoTextBlock
        | LongformDarkBlock
        | PageTitleBlock
        | PostCardsBlock
        | TestimonialsBlock
        | TextColumnsBlock
        | TextCtaBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalendlyEmbedBlock".
 */
export interface CalendlyEmbedBlock {
  background?: ('gray' | 'offwhite' | 'white') | null;
  heading?: string | null;
  annotation?: string | null;
  /**
   * Bijv. https://calendly.com/human-margin-info/30min
   */
  calendlyUrl: string;
  height?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'calendlyEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrushNoteBlock".
 */
export interface BrushNoteBlock {
  /**
   * Marker-lettertype, geel, bovenaan (bijv. "In de Marge"). Leeg laten mag.
   */
  markerHeading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Geel handschrift onder de tekst (bijv. "- Stephan Molle"). Alleen voor de quote-variant.
   */
  attribution?: string | null;
  showForm?: boolean | null;
  formButtonLabel?: string | null;
  /**
   * Optioneel. Leeg = standaard gele penseelstreek.
   */
  brushImage?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'brushNote';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Beschrijving van de afbeelding voor SEO en toegankelijkheid
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardColumnsBlock".
 */
export interface CardColumnsBlock {
  background?: ('gray' | 'offwhite' | 'white' | 'black') | null;
  cards?:
    | {
        heading?: string | null;
        subheading?: string | null;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        cta?: {
          label?: string | null;
          href?: string | null;
          variant?: ('blue' | 'yellow') | null;
        };
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cardColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EbookOptinBlock".
 */
export interface EbookOptinBlock {
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  buttonLabel?: string | null;
  /**
   * Optioneel. Leeg = lege kolom links.
   */
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'ebookOptin';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock".
 */
export interface FaqBlock {
  background?: ('offwhite' | 'white' | 'gray' | 'black') | null;
  heading?: string | null;
  items?:
    | {
        question: string;
        answer: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        id?: string | null;
      }[]
    | null;
  outro?: string | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroPhotoBlock".
 */
export interface HeroPhotoBlock {
  /**
   * Full-width foto; eventuele tekst zit in de foto zelf
   */
  image: number | Media;
  minHeight?: number | null;
  contentPaddingTop?: number | null;
  /**
   * Optioneel. Leeg = desktop-hoogte × 0,45 op mobiel.
   */
  mobileMinHeight?: number | null;
  /**
   * Optioneel. Leeg = desktop-waarde × 0,48 op mobiel.
   */
  mobileContentPaddingTop?: number | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'heroPhoto';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IframeEmbedBlock".
 */
export interface IframeEmbedBlock {
  background?: ('white' | 'offwhite' | 'gray' | 'black') | null;
  heading?: string | null;
  /**
   * Bijv. https://tally.so/embed/b5LLQe?alignLeft=1&hideTitle=1
   */
  url: string;
  height?: number | null;
  maxWidth?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iframeEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkButtonsBlock".
 */
export interface LinkButtonsBlock {
  logo?: (number | null) | Media;
  links?:
    | {
        label: string;
        href: string;
        variant?: ('blue' | 'yellow') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkButtons';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconListBlock".
 */
export interface IconListBlock {
  background?: ('gray' | 'offwhite' | 'white' | 'black') | null;
  heading?: string | null;
  items?:
    | {
        text: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'iconList';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock".
 */
export interface StatementBlock {
  /**
   * Regelbreuken blijven behouden
   */
  heading: string;
  accent?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statement';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitPhotoTextBlock".
 */
export interface SplitPhotoTextBlock {
  background?: ('gray' | 'offwhite' | 'white' | 'black') | null;
  imagePosition?: ('left' | 'right') | null;
  imageTreatment?: ('full' | 'inset') | null;
  image: number | Media;
  annotation?: string | null;
  annotationFont?: ('handwritten' | 'marker') | null;
  annotationColor?: ('blue' | 'yellow') | null;
  annotationPosition?: ('belowHeading' | 'aboveHeading') | null;
  heading?: string | null;
  /**
   * Strakke Archivo-subkop in geel, onder de hoofdkop
   */
  subheading?: string | null;
  headingLevel?: ('h1' | 'h2') | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  arrowList?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  arrowColor?: ('blue' | 'yellow') | null;
  bodyBottom?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  /**
   * Marker-lettertype in geel, onder de tekst (bijv. "Ontvang 'in de marge'"). Voor de nieuwsbrief-variant.
   */
  markerHeading?: string | null;
  showForm?: boolean | null;
  formButtonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'splitPhotoText';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LongformDarkBlock".
 */
export interface LongformDarkBlock {
  heading?: string | null;
  highlight?: string | null;
  bodyTop?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Decoratieve blauwe handgeschreven woorden. Op desktop rond de tekst geplaatst, op mobiel inline.
   */
  annotations?:
    | {
        text: string;
        font?: ('handwritten' | 'marker') | null;
        id?: string | null;
      }[]
    | null;
  framedImage?: (number | null) | Media;
  bodyBottom?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  arrowList?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'longformDark';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageTitleBlock".
 */
export interface PageTitleBlock {
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pageTitle';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostCardsBlock".
 */
export interface PostCardsBlock {
  background?: ('white' | 'offwhite' | 'gray') | null;
  cards?:
    | {
        image?: (number | null) | Media;
        label?: string | null;
        title: string;
        excerpt?: string | null;
        href: string;
        readMore?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'postCards';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock".
 */
export interface TestimonialsBlock {
  heading?: string | null;
  intro?: string | null;
  items?:
    | {
        quote: string;
        name: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsBlock".
 */
export interface TextColumnsBlock {
  background?: ('gray' | 'offwhite' | 'white' | 'black') | null;
  heading?: string | null;
  /**
   * Vinkje = geen minimumhoogte van 630px en kleinere verticale padding. Voor korte vervolgteksten die bij de vorige sectie horen.
   */
  compact?: boolean | null;
  align?: ('left' | 'center') | null;
  columns?:
    | {
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'textColumns';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCtaBlock".
 */
export interface TextCtaBlock {
  background?: ('white' | 'offwhite' | 'gray' | 'black') | null;
  heading?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'textCta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Beheerders beheren gebruikers, kolommen en de prullenbak; teamleden werken in alle domeinen.
   */
  role: 'beheerder' | 'teamlid';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Nieuwsbrief-aanmeldingen via de formulieren op de site
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: number;
  name?: string | null;
  email: string;
  /**
   * Pagina waar de aanmelding vandaan kwam
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations".
 */
export interface Organisation {
  id: number;
  naam: string;
  website?: string | null;
  linkedin?: string | null;
  sector?: string | null;
  logo?: (number | null) | Media;
  notities?: string | null;
  contacten?: {
    docs?: (number | Contact)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  deals?: {
    docs?: (number | Deal)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  projecten?: {
    docs?: (number | Project)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  tags?: string[] | null;
  eigenaar?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  voornaam: string;
  achternaam?: string | null;
  naam?: string | null;
  /**
   * Uniek — dit is de matchsleutel voor nieuwsbriefstatus en latere e-mailkoppeling.
   */
  email: string;
  extraEmails?: string[] | null;
  telefoons?: string[] | null;
  functie?: string | null;
  linkedin?: string | null;
  avatar?: (number | null) | Media;
  organisatie?: (number | null) | Organisation;
  deals?: {
    docs?: (number | Deal)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  bron?: string | null;
  tags?: string[] | null;
  eigenaar?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals".
 */
export interface Deal {
  id: number;
  titel: string;
  bedrag?: number | null;
  valuta?: ('EUR' | 'USD') | null;
  /**
   * Kolom op het pipeline-board. Leeg of verwijderde fase = kolom 'Geen fase'.
   */
  fase?: (number | null) | DealStage;
  uitkomst: 'open' | 'gewonnen' | 'verloren';
  verlorenReden?: string | null;
  verwachteSluitdatum?: string | null;
  kans?: number | null;
  organisatie?: (number | null) | Organisation;
  contactpersoon?: (number | null) | Contact;
  eigenaar?: (number | null) | User;
  position?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-stages".
 */
export interface DealStage {
  id: number;
  _order?: string | null;
  naam: string;
  kleur: 'groen' | 'blauw' | 'paars' | 'rood' | 'oranje' | 'geel' | 'turquoise' | 'roze' | 'grijs';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  naam: string;
  status: 'actief' | 'gepauzeerd' | 'afgerond';
  /**
   * Leeg laten voor interne projecten.
   */
  organisatie?: (number | null) | Organisation;
  deal?: (number | null) | Deal;
  teamleden?: (number | User)[] | null;
  startdatum?: string | null;
  deadline?: string | null;
  omschrijving?: string | null;
  taken?: {
    docs?: (number | Task)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  tags?: string[] | null;
  eigenaar?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks".
 */
export interface Task {
  id: number;
  titel: string;
  /**
   * Kolom op het taken-board. Leeg of verwijderde status = kolom 'Geen status'.
   */
  status?: (number | null) | TaskStatus;
  /**
   * Leeg laten voor een losse taak.
   */
  project?: (number | null) | Project;
  toegewezen?: (number | null) | User;
  deadline?: string | null;
  prioriteit: 'laag' | 'normaal' | 'hoog';
  checklist?:
    | {
        tekst: string;
        klaar?: boolean | null;
        id?: string | null;
      }[]
    | null;
  omschrijving?: string | null;
  position?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-statuses".
 */
export interface TaskStatus {
  id: number;
  _order?: string | null;
  naam: string;
  kleur: 'groen' | 'blauw' | 'paars' | 'rood' | 'oranje' | 'geel' | 'turquoise' | 'roze' | 'grijs';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-items".
 */
export interface ContentItem {
  id: number;
  titel: string;
  /**
   * Waar dit verschijnt. Een blog-kanaal maakt bij status 'Gepland' automatisch een conceptpagina op de site.
   */
  kanaal?: (number | null) | ContentChannel;
  status: 'idee' | 'concept' | 'gepland' | 'gepubliceerd';
  /**
   * Zonder datum verschijnt dit item alleen in de lijstweergave.
   */
  publishDate?: string | null;
  /**
   * Korte werkomschrijving — de echte content leeft in de gekoppelde pagina of het kanaal zelf.
   */
  brief?: string | null;
  /**
   * De sitepagina waar deze content leeft (blogposts).
   */
  gekoppeldePagina?: (number | null) | Page;
  organisatie?: (number | null) | Organisation;
  project?: (number | null) | Project;
  toegewezen?: (number | null) | User;
  publicatielink?: string | null;
  groupId?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-channels".
 */
export interface ContentChannel {
  id: number;
  _order?: string | null;
  naam: string;
  kleur: 'groen' | 'blauw' | 'paars' | 'rood' | 'oranje' | 'geel' | 'turquoise' | 'roze' | 'grijs';
  /**
   * Vast type dat gedrag bepaalt (blog-kanaal koppelt aan sitepagina's). De naam hierboven is vrij te kiezen.
   */
  type: 'blog' | 'nieuwsbrief' | 'linkedin' | 'instagram' | 'overig';
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-docs".
 */
export interface KnowledgeDoc {
  id: number;
  titel: string;
  inhoud?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Leeg = hoofdstuk op het hoogste niveau.
   */
  parent?: (number | null) | KnowledgeDoc;
  zichtbaarheid: 'intern' | 'publiek';
  organisatie?: (number | null) | Organisation;
  project?: (number | null) | Project;
  tags?: string[] | null;
  auteur?: (number | null) | User;
  position?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  type: 'notitie' | 'statuswijziging' | 'systeem' | 'email' | 'boeking';
  /**
   * Korte regel voor de timeline (notities en automatische statuswijzigingen).
   */
  samenvatting?: string | null;
  tekst?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  targets: (
    | {
        relationTo: 'organisations';
        value: number | Organisation;
      }
    | {
        relationTo: 'contacts';
        value: number | Contact;
      }
    | {
        relationTo: 'deals';
        value: number | Deal;
      }
    | {
        relationTo: 'projects';
        value: number | Project;
      }
  )[];
  auteur?: (number | null) | User;
  happensAt: string;
  properties?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'organisations';
        value: number | Organisation;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'deals';
        value: number | Deal;
      } | null)
    | ({
        relationTo: 'deal-stages';
        value: number | DealStage;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'tasks';
        value: number | Task;
      } | null)
    | ({
        relationTo: 'task-statuses';
        value: number | TaskStatus;
      } | null)
    | ({
        relationTo: 'content-items';
        value: number | ContentItem;
      } | null)
    | ({
        relationTo: 'content-channels';
        value: number | ContentChannel;
      } | null)
    | ({
        relationTo: 'knowledge-docs';
        value: number | KnowledgeDoc;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        calendlyEmbed?: T | CalendlyEmbedBlockSelect<T>;
        brushNote?: T | BrushNoteBlockSelect<T>;
        cardColumns?: T | CardColumnsBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        ebookOptin?: T | EbookOptinBlockSelect<T>;
        faq?: T | FaqBlockSelect<T>;
        heroPhoto?: T | HeroPhotoBlockSelect<T>;
        iframeEmbed?: T | IframeEmbedBlockSelect<T>;
        linkButtons?: T | LinkButtonsBlockSelect<T>;
        iconList?: T | IconListBlockSelect<T>;
        statement?: T | StatementBlockSelect<T>;
        splitPhotoText?: T | SplitPhotoTextBlockSelect<T>;
        longformDark?: T | LongformDarkBlockSelect<T>;
        pageTitle?: T | PageTitleBlockSelect<T>;
        postCards?: T | PostCardsBlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        textColumns?: T | TextColumnsBlockSelect<T>;
        textCta?: T | TextCtaBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CalendlyEmbedBlock_select".
 */
export interface CalendlyEmbedBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  annotation?: T;
  calendlyUrl?: T;
  height?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BrushNoteBlock_select".
 */
export interface BrushNoteBlockSelect<T extends boolean = true> {
  markerHeading?: T;
  body?: T;
  attribution?: T;
  showForm?: T;
  formButtonLabel?: T;
  brushImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CardColumnsBlock_select".
 */
export interface CardColumnsBlockSelect<T extends boolean = true> {
  background?: T;
  cards?:
    | T
    | {
        heading?: T;
        subheading?: T;
        body?: T;
        cta?:
          | T
          | {
              label?: T;
              href?: T;
              variant?: T;
            };
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  richText?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EbookOptinBlock_select".
 */
export interface EbookOptinBlockSelect<T extends boolean = true> {
  heading?: T;
  body?: T;
  buttonLabel?: T;
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FaqBlock_select".
 */
export interface FaqBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  items?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  outro?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "HeroPhotoBlock_select".
 */
export interface HeroPhotoBlockSelect<T extends boolean = true> {
  image?: T;
  minHeight?: T;
  contentPaddingTop?: T;
  mobileMinHeight?: T;
  mobileContentPaddingTop?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IframeEmbedBlock_select".
 */
export interface IframeEmbedBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  url?: T;
  height?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkButtonsBlock_select".
 */
export interface LinkButtonsBlockSelect<T extends boolean = true> {
  logo?: T;
  links?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "IconListBlock_select".
 */
export interface IconListBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  items?:
    | T
    | {
        text?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatementBlock_select".
 */
export interface StatementBlockSelect<T extends boolean = true> {
  heading?: T;
  accent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SplitPhotoTextBlock_select".
 */
export interface SplitPhotoTextBlockSelect<T extends boolean = true> {
  background?: T;
  imagePosition?: T;
  imageTreatment?: T;
  image?: T;
  annotation?: T;
  annotationFont?: T;
  annotationColor?: T;
  annotationPosition?: T;
  heading?: T;
  subheading?: T;
  headingLevel?: T;
  body?: T;
  arrowList?:
    | T
    | {
        text?: T;
        id?: T;
      };
  arrowColor?: T;
  bodyBottom?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  markerHeading?: T;
  showForm?: T;
  formButtonLabel?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LongformDarkBlock_select".
 */
export interface LongformDarkBlockSelect<T extends boolean = true> {
  heading?: T;
  highlight?: T;
  bodyTop?: T;
  annotations?:
    | T
    | {
        text?: T;
        font?: T;
        id?: T;
      };
  framedImage?: T;
  bodyBottom?: T;
  arrowList?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PageTitleBlock_select".
 */
export interface PageTitleBlockSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PostCardsBlock_select".
 */
export interface PostCardsBlockSelect<T extends boolean = true> {
  background?: T;
  cards?:
    | T
    | {
        image?: T;
        label?: T;
        title?: T;
        excerpt?: T;
        href?: T;
        readMore?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlock_select".
 */
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  items?:
    | T
    | {
        quote?: T;
        name?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextColumnsBlock_select".
 */
export interface TextColumnsBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  compact?: T;
  align?: T;
  columns?:
    | T
    | {
        body?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextCtaBlock_select".
 */
export interface TextCtaBlockSelect<T extends boolean = true> {
  background?: T;
  heading?: T;
  body?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisations_select".
 */
export interface OrganisationsSelect<T extends boolean = true> {
  naam?: T;
  website?: T;
  linkedin?: T;
  sector?: T;
  logo?: T;
  notities?: T;
  contacten?: T;
  deals?: T;
  projecten?: T;
  tags?: T;
  eigenaar?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  voornaam?: T;
  achternaam?: T;
  naam?: T;
  email?: T;
  extraEmails?: T;
  telefoons?: T;
  functie?: T;
  linkedin?: T;
  avatar?: T;
  organisatie?: T;
  deals?: T;
  bron?: T;
  tags?: T;
  eigenaar?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deals_select".
 */
export interface DealsSelect<T extends boolean = true> {
  titel?: T;
  bedrag?: T;
  valuta?: T;
  fase?: T;
  uitkomst?: T;
  verlorenReden?: T;
  verwachteSluitdatum?: T;
  kans?: T;
  organisatie?: T;
  contactpersoon?: T;
  eigenaar?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "deal-stages_select".
 */
export interface DealStagesSelect<T extends boolean = true> {
  _order?: T;
  naam?: T;
  kleur?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  naam?: T;
  status?: T;
  organisatie?: T;
  deal?: T;
  teamleden?: T;
  startdatum?: T;
  deadline?: T;
  omschrijving?: T;
  taken?: T;
  tags?: T;
  eigenaar?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tasks_select".
 */
export interface TasksSelect<T extends boolean = true> {
  titel?: T;
  status?: T;
  project?: T;
  toegewezen?: T;
  deadline?: T;
  prioriteit?: T;
  checklist?:
    | T
    | {
        tekst?: T;
        klaar?: T;
        id?: T;
      };
  omschrijving?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "task-statuses_select".
 */
export interface TaskStatusesSelect<T extends boolean = true> {
  _order?: T;
  naam?: T;
  kleur?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-items_select".
 */
export interface ContentItemsSelect<T extends boolean = true> {
  titel?: T;
  kanaal?: T;
  status?: T;
  publishDate?: T;
  brief?: T;
  gekoppeldePagina?: T;
  organisatie?: T;
  project?: T;
  toegewezen?: T;
  publicatielink?: T;
  groupId?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-channels_select".
 */
export interface ContentChannelsSelect<T extends boolean = true> {
  _order?: T;
  naam?: T;
  kleur?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "knowledge-docs_select".
 */
export interface KnowledgeDocsSelect<T extends boolean = true> {
  titel?: T;
  inhoud?: T;
  parent?: T;
  zichtbaarheid?: T;
  organisatie?: T;
  project?: T;
  tags?: T;
  auteur?: T;
  position?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  type?: T;
  samenvatting?: T;
  tekst?: T;
  targets?: T;
  auteur?: T;
  happensAt?: T;
  properties?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
    variant?: ('blue' | 'yellow') | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  followLabel?: string | null;
  socials?:
    | {
        platform: 'linkedin' | 'instagram' | 'x' | 'youtube';
        href: string;
        id?: string | null;
      }[]
    | null;
  menu?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  contactLabel?: string | null;
  contactEmail?: string | null;
  copyright?: string | null;
  credit?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        variant?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  followLabel?: T;
  socials?:
    | T
    | {
        platform?: T;
        href?: T;
        id?: T;
      };
  menu?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  contactLabel?: T;
  contactEmail?: T;
  copyright?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}